### PR TITLE
Warehouse code to restocking 298

### LINKED ISSUE #298: Add Warehouse Code to Restocking Page
Image

Example:
Image

### PR DESCRIPTION
**Pull request by robgoodliffe**
closes #298

### CODE REVIEW

**Comment by ArturHanusek** [comment]
@robgoodliffe 

big gap on mobile
image

**Comment by robgoodliffe** [comment]
@ArturHanusek lessened gap. Let me know if thats ok.

**Comment by ArturHanusek** [comment]
@robgoodliffe there is no need for gap at all, waste of space on mobile device... just remove it

**Comment by robgoodliffe** [comment]
@ArturHanusek removed

**Pull request merged**
