### PR TITLE
Laravel 11.x Shift

### PR DESCRIPTION
**Pull request by Rafnexx**
This pull request includes the changes for upgrading to Laravel 11.x. Feel free to commit any additional changes to the `shift-128804` branch.

**Before merging**, you need to:

- Checkout the `shift-128804` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, try with `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts).

### CODE REVIEW

**Comment by Rafnexx** [comment]
:information_source: To slim down the Laravel installation, Laravel 11 no longer has most of the core files previously included in the default Laravel application. While you are welcome to publish and customize these files, they are no longer required.

Shift takes an iterative approach to removing core files which are not customized or where its customizations may be done elsewhere in a modern Laravel 11 application. As such, you may see some commits removing files and others _re-registering_ your customizations.

**Comment by Rafnexx** [comment]
:warning: The application bootstrapping changed in Laravel 11. As a result, files like `artisan` and `public/index.php` were rewritten. Shift [overwrote these files](https://github.com/CodingCab/ShipTown/pull/561/commits/1213395c4767a2ae37e2792b9a41d227783adb36?w=1) but detected yours may have contained customizations. You should review the diff to see if any of your customizations are still needed.

**Comment by Rafnexx** [comment]
:information_source: Laravel 11 no longer requires you to maintain the default configuration files. Your configuration [now merges with framework defaults](https://laravel-news.com/laravel11-streamlined-configs). 

Shift [streamlined your configuration files](https://github.com/CodingCab/ShipTown/pull/561/commits/cf6c5616ea14ef9800d863704cafe4dd9be8f20e?w=1) by removing options that matched the Laravel defaults and preserving your _true customizations_. These are values which are not changeable through `ENV` variables.

If you wish to keep the full set of configuration files, Shift recommends running `artisan config:publish --all --force` to get the latest configuration files from Laravel 11, then reapplying the customizations Shift streamlined.

**Comment by Rafnexx** [comment]
:information_source: Shift detected customized options within your configuration files which may be set with an `ENV` variable. To help keep your configuration files streamlined, you may set the following variables. Be sure adjust any values per environment.

```txt
BCRYPT_ROUNDS=10
CACHE_STORE=file
DB_CONNECTION=mysql
MAIL_MAILER=smtp
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
```

**Note:** some of these may simply be values which changed between Laravel versions. You may ignore any `ENV` variables you do not need to customize.

**Comment by Rafnexx** [comment]
:information_source: Shift detected your application uses custom `ENV` variables for configuration options which have `ENV` variables in Laravel. Shift recommends renaming the following variables to use the one provided by Laravel:

- [ ] `TIMEZONE` to `APP_TIMEZONE`

**Comment by Rafnexx** [comment]
:warning: The `BROADCAST_DRIVER`, `CACHE_DRIVER`, and `DATABASE_URL` environment variables were renamed in Laravel 11 to `BROADCAST_CONNECTION`, `CACHE_STORE`, and `DB_URL`, respectively.

Shift [automated this change](https://github.com/CodingCab/ShipTown/pull/561/commits/2a199cbfd335a1647e837829ed5c3339fad17ba6?w=1) for your committed files, but you should review any additional locations where your environment is configured and update to the new variable names.

**Comment by Rafnexx** [comment]
:x: The `bootstrap/app.php` file has been completely rewritten in Laravel 11 to allow configuring your Laravel application in a single location. Shift [overwrote your file](https://github.com/CodingCab/ShipTown/pull/561/commits/b7300acc9070daa164d474c93831b72f2d04ae38?w=1), but detected it may have contained customizations. You should review the diff to see if any of your customizations are still needed.

**Comment by Rafnexx** [comment]
:warning: Laravel 11 automatically discovers policies scanning your application's `Policies` directory at or above the directory containing your models.

Shift detected policies registered with the `policies` property of your `AuthServiceProvider`. If any of these policies can not be automatically discovered, you may register them manually using `Gate::policy()` in your `AppServiceProvider`.

**Comment by Rafnexx** [comment]
:warning: Shift was unable to re-register your exception handler. You may [review the documentation](https://laravel.com/docs/11.x/errors#handling-exceptions) to do so manually, or register your original exception handler by adding the following binding to the `register` method of your `AppServiceProvider`:

```php
$this->app->bind(\Illuminate\Contracts\Debug\ExceptionHandler::class, \App\Exceptions\Handler::class);
```

**Comment by Rafnexx** [comment]
:information_source: Shift [updated your dependencies](https://github.com/CodingCab/ShipTown/pull/561/commits/c0552441f89880ac9a607232226209d8724629b8?w=1) for Laravel 11. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 11. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any Composer issues.

The following dependencies **were updated by a major version** and may have their own changes. You may check their changelog for any additional upgrade steps.

- [barryvdh/laravel-ide-helper](https://packagist.org/packages/barryvdh/laravel-ide-helper)
- [laravel/passport](https://packagist.org/packages/laravel/passport)
- [laravel/telescope](https://packagist.org/packages/laravel/telescope)
- [milon/barcode](https://packagist.org/packages/milon/barcode)
- [spatie/laravel-permission](https://packagist.org/packages/spatie/laravel-permission)


The following dependencies **were not updated by Shift** and may be incompatible. If Composer lists one of these packages as a problem, you should check for a newer version.

- [beyondcode/laravel-query-detector](https://packagist.org/packages/beyondcode/laravel-query-detector)
- [hulkur/laravel-hasmany-keyby](https://packagist.org/packages/hulkur/laravel-hasmany-keyby)

**Comment by Rafnexx** [comment]
:warning: Shift detected your application has a test suite. To provide you with a compatible set of dependencies, Shift bumped your version of `phpunit/phpunit` to `^10.5`. While your test suite may still run, you are encouraged to run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free to fully upgrade your test suite to PHPUnit 10.

**Comment by Rafnexx** [comment]
:warning: In Laravel 11, changing a column now requires you to include all the modifiers you want to keep on the column definition after it is changed. Any missing attributes will be dropped. This change may cause unexpected behavior if you were to run pending or old migrations.

Shift detected potential uses of the `change` method within your migrations. While you may go back and update these migrations, you may wish to simply [squash your old migrations](https://laravel.com/docs/11.x/migrations#squashing-migrations). This will not only avoid rework, but may also improve the performance of your test suite.

**Comment by Rafnexx** [comment]
:warning: Many first-party Laravel packages, as well as community packages, removed their `ignoreMigrations` method since they no longer load migrations automatically. Shift detected calls to this method in the following files. You should review these instances to see if they may be removed.

- [ ] [app/Providers/AppServiceProvider.php](https://github.com/CodingCab/ShipTown/blob/716464cc3e78fd92930de033044ca06772c94805/app/Providers/AppServiceProvider.php#L60)

**Comment by Rafnexx** [comment]
:warning: Laravel 11 has a `nesbot/carbon` dependency of `^2.72|^3.0`. Carbon 3.0 made some breaking changes. Most notably to the `diffIn*` methods and the removal of the `setUtf8`, `formatLocalized`, `setWeekStartsAt`, `setWeekEndsAt` methods. While you may try to downgrade to Carbon 2, Shift recommends you review the [Carbon migration notes](https://carbon.nesbot.com/docs/#/upgrade-3.0) and complete the upgrade to Carbon 3.0.

Shift detected uses of these methods in the following files:

- [ ] [app/Models/Order.php](https://github.com/CodingCab/ShipTown/blob/716464cc3e78fd92930de033044ca06772c94805/app/Models/Order.php#L259)
- [ ] [app/Models/OrderShipment.php](https://github.com/CodingCab/ShipTown/blob/716464cc3e78fd92930de033044ca06772c94805/app/Models/OrderShipment.php#L94)
- [ ] [app/Modules/QueueMonitor/src/Listeners/JobFailedListener.php](https://github.com/CodingCab/ShipTown/blob/716464cc3e78fd92930de033044ca06772c94805/app/Modules/QueueMonitor/src/Listeners/JobFailedListener.php#L24)
- [ ] [app/Modules/QueueMonitor/src/Listeners/JobProcessedListener.php](https://github.com/CodingCab/ShipTown/blob/716464cc3e78fd92930de033044ca06772c94805/app/Modules/QueueMonitor/src/Listeners/JobProcessedListener.php#L24)
- [ ] [app/Widgets/Apt.php](https://github.com/CodingCab/ShipTown/blob/716464cc3e78fd92930de033044ca06772c94805/app/Widgets/Apt.php#L50)
- [ ] [app/Widgets/OrdersByAgeWidget.php](https://github.com/CodingCab/ShipTown/blob/716464cc3e78fd92930de033044ca06772c94805/app/Widgets/OrdersByAgeWidget.php#L43)

**Comment by Rafnexx** [comment]
:information_source: Laravel 11 now updates the timestamp when publishing vendor migrations. This may cause problems in existing applications when these migrations were previously published and ran with their default timestamp.

To preserve the original behavior, Shift disabled this feature in your `database.php` configuration file. If you do not have any vendor migrations or have squashed all of your existing migrations, you may re-enable the `update_date_on_publish` option. If this is the only customization within `database.php`, you may remove this configuration file.

**Comment by Rafnexx** [comment]
:information_source: The following files previously included in a Laravel application appeared to be customized and were not removed. Shift encourages you to review your customizations to see if they are still needed or may be done elsewhere in a modern Laravel application. Removing these files will keep your application modern and make future maintenance easier.

- [ ] app/Providers/EventServiceProvider.php
- [ ] app/Providers/RouteServiceProvider.php

**Comment by Rafnexx** [comment]
:warning: Previously, Laravel would append a colon (`:`) to any cache key prefix for DynamoDB, Memcache, or Redis. Laravel 11 no longer appends a colon to your cache key prefix. If you are using one of these stores, you should append a colon to your prefix to avoid invalidating your cache.

**Comment by Rafnexx** [comment]
:warning: Many of the default drivers changed in Laravel 11. For example, the default database driver is `sqlite` and the default cache store is `database`. If you experience errors setting up your environment, be sure you have properly set your `ENV` variables for these drivers. If you wish to adopt the new defaults, you may follow the documentation to set them up for your application.

**Comment by Rafnexx** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 7.0. Shift detected references to Symfony classes within your application. These are most likely type hints and can safely be ignored. If you are using Symfony classes directly or experience issues relating to Symfony, you should review the [Symfony change log](https://github.com/symfony/symfony/blob/7.0/UPGRADE-7.0.md) for any additional changes.

**Comment by Rafnexx** [comment]
:warning: Laravel 11 requires PHP 8.2 or higher. You should verify the PHP version in your environments to ensure it meets this new requirement.

**Comment by Rafnexx** [comment]
:warning: Laravel 11 now includes a database driver for MariaDB. Previously the MySQL driver offered parity with MariaDB. However, with MariaDB 10.1, there are more database specific features available. If you are using MariaDB, you may want to evaluate this new `mariadb` driver after completing your upgrade to Laravel 11.

**Comment by Rafnexx** [comment]
:warning: Shift detected you are using a Laravel package like Horizon or Nova which may need to have its published assets regenerated after upgrading. Be sure to use `artisan` to _republish_ these assets as well as `php artisan view:clear` to avoid any errors.

**Comment by Rafnexx** [comment]
:tada: Congratulations, you're now running the latest version of Laravel!

Next, you may optionally run the following _Shifts_ to ensure your application is fully upgraded, adopts the latest Laravel conventions, and easier to maintain in the future:

- [Laravel Fixer](https://laravelshift.com/laravel-code-fixer) automatically updates your code to the latest Laravel conventions.
- [Tests Generator](https://laravelshift.com/laravel-test-generator) intelligently generates model factories, HTTP Tests, and configuration for your application.
- [CI Generator](https://laravelshift.com/ci-generator) intelligently generates CI jobs to lint PHP, check code style, and run tests, including Dusk.

You may also use the [Shift Workbench](https://laravelshift.com/workbench) to automate common tasks for maintaining your Laravel application.

**Review by ArturHanusek — APPROVED** [review]

**Pull request merged**
